const MEDIA = 'MEDIA';
const DEVICE = 'DEVICE';
const TRACK = 'TRACK';
const MEDIA_STREAM_TRACK = 'MEDIA_STREAM_TRACK';
const MEDIA_CONNECTION = 'MEDIA_CONNECTION';
const ROAP_MEDIA_CONNECTION = 'ROAP_MEDIA_CONNECTION';
const ROAP = 'ROAP';

export {DEVICE, MEDIA, MEDIA_CONNECTION, ROAP, ROAP_MEDIA_CONNECTION, TRACK, MEDIA_STREAM_TRACK};
