// SDPs generated by browsers always have CRLF (\r\n) endings,
// here we're using tagged template literals to ensures that our SDP fixtures also have CRLF endings
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const ensureCRLF = (strings: any, ...tags: string[]) => {
  const stringsWithCRLF = strings.raw.map((str: string) => str.replace(/\n/g, '\r\n'));

  // now construct the output the same way as it's done by default for template literals
  let output = stringsWithCRLF[0];

  tags.forEach((tag, index) => {
    output += tag + stringsWithCRLF[index + 1];
  });

  return output;
};

// a cut down version of SDP taken from chrome with port value 9 for audio and one of video m-lines
export const SDP_WITH_PORT_9_VALUE = ensureCRLF`v=0
o=- 2935832218733659974 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 103
c=IN IP4 0.0.0.0
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=ice-options:trickle
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 36193 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:0
a=rtcp-mux
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtcp:9 IN IP4 0.0.0.0
a=msid:- cc26c00b-a7b8-463c-bab5-821a50cd6acd
a=ssrc:3091196375 cname:zEw239i8VYqeJ/C7
a=ssrc:3091196375 msid:- cc26c00b-a7b8-463c-bab5-821a50cd6acd
a=ssrc:3091196375 mslabel:-
a=ssrc:3091196375 label:cc26c00b-a7b8-463c-bab5-821a50cd6acd
m=video 5094 UDP/TLS/RTP/SAVPF 96 97
c=IN IP4 0.0.0.0
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=ice-options:trickle
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 52772 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:1
a=rtcp-mux
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtcp:9 IN IP4 0.0.0.0
a=msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=rtcp-rsize
a=ssrc-group:FID 870163895 424273468
a=ssrc:870163895 cname:zEw239i8VYqeJ/C7
a=ssrc:870163895 msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:870163895 mslabel:-
a=ssrc:870163895 label:4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:424273468 cname:zEw239i8VYqeJ/C7
a=ssrc:424273468 msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:424273468 mslabel:-
a=ssrc:424273468 label:4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
m=video 9 UDP/TLS/RTP/SAVPF 102 124 127
c=IN IP4 0.0.0.0
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=ice-options:trickle
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 37908 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:2
a=rtcp-mux
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=inactive
a=rtpmap:102 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=102
a=rtpmap:127 ulpfec/90000
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-rsize
`;

// exactly the same like SDP_WITH_PORT_9_VALUE, but with the port values in the m-lines changed from 9 to 0
export const SDP_WITH_PORT_9_VALUE_CONVERTED_TO_0 = ensureCRLF`v=0
o=- 2935832218733659974 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 0 UDP/TLS/RTP/SAVPF 111 103
c=IN IP4 0.0.0.0
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=ice-options:trickle
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 36193 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:0
a=rtcp-mux
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtcp:9 IN IP4 0.0.0.0
a=msid:- cc26c00b-a7b8-463c-bab5-821a50cd6acd
a=ssrc:3091196375 cname:zEw239i8VYqeJ/C7
a=ssrc:3091196375 msid:- cc26c00b-a7b8-463c-bab5-821a50cd6acd
a=ssrc:3091196375 mslabel:-
a=ssrc:3091196375 label:cc26c00b-a7b8-463c-bab5-821a50cd6acd
m=video 5094 UDP/TLS/RTP/SAVPF 96 97
c=IN IP4 0.0.0.0
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=ice-options:trickle
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 52772 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:1
a=rtcp-mux
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtcp:9 IN IP4 0.0.0.0
a=msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=rtcp-rsize
a=ssrc-group:FID 870163895 424273468
a=ssrc:870163895 cname:zEw239i8VYqeJ/C7
a=ssrc:870163895 msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:870163895 mslabel:-
a=ssrc:870163895 label:4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:424273468 cname:zEw239i8VYqeJ/C7
a=ssrc:424273468 msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:424273468 mslabel:-
a=ssrc:424273468 label:4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
m=video 0 UDP/TLS/RTP/SAVPF 102 124 127
c=IN IP4 0.0.0.0
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=ice-options:trickle
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 37908 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:2
a=rtcp-mux
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=inactive
a=rtpmap:102 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=102
a=rtpmap:127 ulpfec/90000
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-rsize
`;

export const SDP_WITH_1_VIDEO_M_LINE = ensureCRLF`v=0
o=- 2935832218733659974 2 IN IP4 127.0.0.1
s=-
c=IN IP4 0.0.0.0
t=0 0
a=group:BUNDLE 0 1
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
m=audio 9 UDP/TLS/RTP/SAVPF 103
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:0
a=sendrecv
a=rtpmap:103 ISAC/16000
a=ssrc:3091196375 cname:zEw239i8VYqeJ/C7
a=ssrc:3091196375 msid:- cc26c00b-a7b8-463c-bab5-821a50cd6acd
m=video 5094 UDP/TLS/RTP/SAVPF 96
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:1
a=sendonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:870163895 cname:zEw239i8VYqeJ/C7
`;

// SDP with ice candidates, 2 video m-lines and both are without H264
export const SDP_WITH_2_VIDEO_M_LINES_AND_NO_H264 = ensureCRLF`v=0
o=- 2935832218733659974 2 IN IP4 127.0.0.1
s=-
c=IN IP4 0.0.0.0
t=0 0
a=group:BUNDLE 0 1 2
m=audio 9 UDP/TLS/RTP/SAVPF 103
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:0
a=sendrecv
a=rtpmap:103 ISAC/16000
a=ssrc:3091196375 cname:zEw239i8VYqeJ/C7
a=ssrc:3091196375 msid:- cc26c00b-a7b8-463c-bab5-821a50cd6acd
m=video 5094 UDP/TLS/RTP/SAVPF 96
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:1
a=sendonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:870163895 cname:zEw239i8VYqeJ/C7
m=video 9 UDP/TLS/RTP/SAVPF 102 124 127
c=IN IP4 0.0.0.0
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 37908 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:2
a=inactive
a=rtpmap:102 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=102
a=rtpmap:127 ulpfec/90000
a=rtcp:9 IN IP4 0.0.0.0
`;

export const SDP_WITH_2_VIDEO_M_LINES = ensureCRLF`v=0
o=- 2935832218733659974 2 IN IP4 127.0.0.1
s=-
c=IN IP4 0.0.0.0
t=0 0
a=group:BUNDLE 0 1 2
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
m=audio 9 UDP/TLS/RTP/SAVPF 103
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:0
a=sendrecv
a=rtpmap:103 ISAC/16000
a=ssrc:3091196375 cname:zEw239i8VYqeJ/C7
a=ssrc:3091196375 msid:- cc26c00b-a7b8-463c-bab5-821a50cd6acd
m=video 5094 UDP/TLS/RTP/SAVPF 96
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:1
a=sendonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:870163895 cname:zEw239i8VYqeJ/C7
m=video 9 UDP/TLS/RTP/SAVPF 102 124 127
c=IN IP4 0.0.0.0
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=ice-options:trickle
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 37908 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:2
a=inactive
a=rtpmap:102 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=102
a=rtpmap:127 ulpfec/90000
a=rtcp:9 IN IP4 0.0.0.0
`;

// same as SDP_WITH_2_VIDEO_M_LINES but with "a=content:slide" line in 2nd video m-line section
export const SDP_WITH_2_VIDEO_M_LINES_AND_CONTENT_SLIDES = ensureCRLF`v=0
o=- 2935832218733659974 2 IN IP4 127.0.0.1
s=-
c=IN IP4 0.0.0.0
t=0 0
a=group:BUNDLE 0 1 2
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
m=audio 9 UDP/TLS/RTP/SAVPF 103
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:0
a=sendrecv
a=rtpmap:103 ISAC/16000
a=ssrc:3091196375 cname:zEw239i8VYqeJ/C7
a=ssrc:3091196375 msid:- cc26c00b-a7b8-463c-bab5-821a50cd6acd
m=video 5094 UDP/TLS/RTP/SAVPF 96
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:1
a=sendonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:870163895 cname:zEw239i8VYqeJ/C7
m=video 9 UDP/TLS/RTP/SAVPF 102 124 127
c=IN IP4 0.0.0.0
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=ice-options:trickle
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 37908 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:2
a=content:slides
a=inactive
a=rtpmap:102 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=102
a=rtpmap:127 ulpfec/90000
a=rtcp:9 IN IP4 0.0.0.0
`;

// same as SDP_WITH_2_VIDEO_M_LINES but with b=TIAS lines added in each m-section and a=periodic-keyframes in video sections
export const SDP_WITH_2_VIDEO_M_LINES_AND_BANDWIDTH_LIMITS = ensureCRLF`v=0
o=- 2935832218733659974 2 IN IP4 127.0.0.1
s=-
c=IN IP4 0.0.0.0
t=0 0
a=group:BUNDLE 0 1 2
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
m=audio 9 UDP/TLS/RTP/SAVPF 103
b=TIAS:1024
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:0
a=sendrecv
a=rtpmap:103 ISAC/16000
a=ssrc:3091196375 cname:zEw239i8VYqeJ/C7
a=ssrc:3091196375 msid:- cc26c00b-a7b8-463c-bab5-821a50cd6acd
m=video 5094 UDP/TLS/RTP/SAVPF 96
b=TIAS:4096
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:1
a=sendonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:870163895 cname:zEw239i8VYqeJ/C7
a=periodic-keyframes:20
m=video 9 UDP/TLS/RTP/SAVPF 102 124 127
c=IN IP4 0.0.0.0
b=TIAS:4096
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=ice-options:trickle
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 37908 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:2
a=inactive
a=rtpmap:102 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=102
a=rtpmap:127 ulpfec/90000
a=rtcp:9 IN IP4 0.0.0.0
a=periodic-keyframes:20
`;

export const SDP_WITH_IPV6_C_LINES = ensureCRLF`v=0
o=- 2935832218733659974 2 IN IP4 127.0.0.1
s=-
c=IN IP6 2001::5ef5:79fd:1cdf:b0f:b981:52c7
t=0 0
a=group:BUNDLE 0 1 2
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
m=audio 9 UDP/TLS/RTP/SAVPF 103
c=IN IP6 684D:1111:222:3333:4444:5555:6:77
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:0
a=sendrecv
a=rtpmap:103 ISAC/16000
a=ssrc:3091196375 cname:zEw239i8VYqeJ/C7
a=ssrc:3091196375 msid:- cc26c00b-a7b8-463c-bab5-821a50cd6acd
m=video 5094 UDP/TLS/RTP/SAVPF 96
c=IN IP6 2001:db8:85a3:8d3:1319:8a2e:370:7348
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:1
a=sendonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:870163895 cname:zEw239i8VYqeJ/C7
m=video 9 UDP/TLS/RTP/SAVPF 102 124 127
c=IN IP6 2a02:c7f:60d6:2600:4157:2f9c:198b:80a3
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=ice-options:trickle
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 37908 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:2
a=inactive
a=rtpmap:102 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=102
a=rtpmap:127 ulpfec/90000
a=rtcp:9 IN IP4 0.0.0.0
`;

// same like SDP_WITH_IPV6_C_LINES but with IPv4 0.0.0.0 instead of IPv6 values
export const SDP_WITH_IPV4_C_LINES = ensureCRLF`v=0
o=- 2935832218733659974 2 IN IP4 127.0.0.1
s=-
c=IN IP4 0.0.0.0
t=0 0
a=group:BUNDLE 0 1 2
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
m=audio 9 UDP/TLS/RTP/SAVPF 103
c=IN IP4 0.0.0.0
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:0
a=sendrecv
a=rtpmap:103 ISAC/16000
a=ssrc:3091196375 cname:zEw239i8VYqeJ/C7
a=ssrc:3091196375 msid:- cc26c00b-a7b8-463c-bab5-821a50cd6acd
m=video 5094 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:1
a=sendonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=msid:- 4cfa6ba7-60d9-49ce-9e48-bfecdcf4ef50
a=ssrc:870163895 cname:zEw239i8VYqeJ/C7
m=video 9 UDP/TLS/RTP/SAVPF 102 124 127
c=IN IP4 0.0.0.0
a=ice-ufrag:1izm
a=ice-pwd:LH+BRR+d0AN0wUfhri7wyRII
a=ice-options:trickle
a=candidate:3964964154 1 udp 2113937151 4a52ecb2-bfd3-4f08-8479-4ed6029555f3.local 37908 typ host generation 0 network-cost 999
a=fingerprint:sha-256 EC:C5:A0:3A:07:61:A6:1C:44:EC:E6:14:31:54:45:86:DB:2B:87:D7:F5:06:11:93:5F:2A:07:F8:FB:C2:DE:5E
a=setup:actpass
a=mid:2
a=inactive
a=rtpmap:102 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=102
a=rtpmap:127 ulpfec/90000
a=rtcp:9 IN IP4 0.0.0.0
`;

// example SDP that has an audio and 2 video m-lines, video contains multiple codecs
// it's basically a trimmed down version of an SDP example from Chrome
export const SDP_MULTIPLE_VIDEO_CODECS = ensureCRLF`v=0
o=- 3328550572590672467 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS 38872d1a-f4c3-4234-b162-bb47bc55ec57
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 106
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:0
a=rtcp-mux
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
a=ssrc:3693867886 cname:TGydLcYyPoQiRBlB
a=ssrc:3693867886 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
m=video 9 UDP/TLS/RTP/SAVPF 100 101 127 121 114 115 116 117 118
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:1
a=rtcp-mux
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:114 H264/90000
a=rtcp-fb:114 goog-remb
a=rtcp-fb:114 transport-cc
a=rtcp-fb:114 ccm fir
a=rtcp-fb:114 nack
a=rtcp-fb:114 nack pli
a=fmtp:114 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 red/90000
a=rtpmap:117 rtx/90000
a=fmtp:117 apt=116
a=rtpmap:118 ulpfec/90000
a=rtcp-rsize
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
a=ssrc:597013044 cname:TGydLcYyPoQiRBlB
a=ssrc:597013044 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
m=video 9 UDP/TLS/RTP/SAVPF 102 122 127 121 108 109
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:2
a=rtcp-mux
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtpmap:102 VP9/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 profile-id=1
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtcp-rsize
a=rtcp:9 IN IP4 0.0.0.0
`;

// same as SDP_MULTIPLE_VIDEO_CODECS, but with RTX payload types removed
export const SDP_MULTIPLE_VIDEO_CODECS_WITHOUT_RTX = ensureCRLF`v=0
o=- 3328550572590672467 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS 38872d1a-f4c3-4234-b162-bb47bc55ec57
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 106
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:0
a=rtcp-mux
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
a=ssrc:3693867886 cname:TGydLcYyPoQiRBlB
a=ssrc:3693867886 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
m=video 9 UDP/TLS/RTP/SAVPF 100 127 114 116 118
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:1
a=rtcp-mux
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:114 H264/90000
a=rtcp-fb:114 goog-remb
a=rtcp-fb:114 transport-cc
a=rtcp-fb:114 ccm fir
a=rtcp-fb:114 nack
a=rtcp-fb:114 nack pli
a=fmtp:114 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
a=rtpmap:116 red/90000
a=rtpmap:118 ulpfec/90000
a=rtcp-rsize
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
a=ssrc:597013044 cname:TGydLcYyPoQiRBlB
a=ssrc:597013044 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
m=video 9 UDP/TLS/RTP/SAVPF 102 127 108
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:2
a=rtcp-mux
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtpmap:102 VP9/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 profile-id=1
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-rsize
a=rtcp:9 IN IP4 0.0.0.0
`;

// same as SDP_MULTIPLE_VIDEO_CODECS, but has x-google-start-bitrate appended to all H264 fmtp lines
export const SDP_MULTIPLE_VIDEO_CODECS_WITH_START_BITRATE = ensureCRLF`v=0
o=- 3328550572590672467 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS 38872d1a-f4c3-4234-b162-bb47bc55ec57
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 106
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:0
a=rtcp-mux
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
a=ssrc:3693867886 cname:TGydLcYyPoQiRBlB
a=ssrc:3693867886 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
m=video 9 UDP/TLS/RTP/SAVPF 100 101 127 121 114 115 116 117 118
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:1
a=rtcp-mux
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f;x-google-start-bitrate=1000
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:114 H264/90000
a=rtcp-fb:114 goog-remb
a=rtcp-fb:114 transport-cc
a=rtcp-fb:114 ccm fir
a=rtcp-fb:114 nack
a=rtcp-fb:114 nack pli
a=fmtp:114 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f;x-google-start-bitrate=1000
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 red/90000
a=rtpmap:117 rtx/90000
a=fmtp:117 apt=116
a=rtpmap:118 ulpfec/90000
a=rtcp-rsize
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
a=ssrc:597013044 cname:TGydLcYyPoQiRBlB
a=ssrc:597013044 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
m=video 9 UDP/TLS/RTP/SAVPF 102 122 127 121 108 109
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:2
a=rtcp-mux
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtpmap:102 VP9/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 profile-id=1
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f;x-google-start-bitrate=1000
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f;x-google-start-bitrate=1000
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtcp-rsize
a=rtcp:9 IN IP4 0.0.0.0
`;

// same as SDP_MULTIPLE_VIDEO_CODECS, but has max-fs appended to all H264 fmtp lines
export const SDP_MULTIPLE_VIDEO_CODECS_WITH_MAX_FS = ensureCRLF`v=0
o=- 3328550572590672467 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS 38872d1a-f4c3-4234-b162-bb47bc55ec57
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 106
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:0
a=rtcp-mux
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
a=ssrc:3693867886 cname:TGydLcYyPoQiRBlB
a=ssrc:3693867886 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
m=video 9 UDP/TLS/RTP/SAVPF 100 101 127 121 114 115 116 117 118
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:1
a=rtcp-mux
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f;max-fs=8192
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:114 H264/90000
a=rtcp-fb:114 goog-remb
a=rtcp-fb:114 transport-cc
a=rtcp-fb:114 ccm fir
a=rtcp-fb:114 nack
a=rtcp-fb:114 nack pli
a=fmtp:114 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f;max-fs=8192
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 red/90000
a=rtpmap:117 rtx/90000
a=fmtp:117 apt=116
a=rtpmap:118 ulpfec/90000
a=rtcp-rsize
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
a=ssrc:597013044 cname:TGydLcYyPoQiRBlB
a=ssrc:597013044 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
m=video 9 UDP/TLS/RTP/SAVPF 102 122 127 121 108 109
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=candidate:1 1 udp 2130706431 10.50.173.46 56821 typ host
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:2
a=rtcp-mux
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtpmap:102 VP9/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 profile-id=1
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f;max-fs=8192
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f;max-fs=8192
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtcp-rsize
a=rtcp:9 IN IP4 0.0.0.0
`;

// SDP with many extmap lines in each m-section
export const SDP_WITH_EXTMAP = ensureCRLF`v=0
o=- 3328550572590672467 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS 38872d1a-f4c3-4234-b162-bb47bc55ec57
m=audio 9 UDP/TLS/RTP/SAVPF 111 9 0 8
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtcp-mux
a=sendrecv
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
a=ssrc:3693867886 cname:TGydLcYyPoQiRBlB
a=ssrc:3693867886 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=rtcp-mux
a=sendrecv
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
a=rtcp-rsize
a=ssrc:2123144679 cname:TGydLcYyPoQiRBlB
a=ssrc:2123144679 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:2
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=rtcp-mux
a=recvonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-rsize
`;

// same as SDP_WITH_EXTMAP but with all rtp extension header lines removed
export const SDP_WITH_EXTMAP_REMOVED = ensureCRLF`v=0
o=- 3328550572590672467 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS 38872d1a-f4c3-4234-b162-bb47bc55ec57
m=audio 9 UDP/TLS/RTP/SAVPF 111 9 0 8
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:0
a=rtcp-mux
a=sendrecv
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
a=ssrc:3693867886 cname:TGydLcYyPoQiRBlB
a=ssrc:3693867886 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 0283c960-c78d-4164-a6f3-394342273ad4
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:1
a=rtcp-mux
a=sendrecv
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp:9 IN IP4 0.0.0.0
a=msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
a=rtcp-rsize
a=ssrc:2123144679 cname:TGydLcYyPoQiRBlB
a=ssrc:2123144679 msid:38872d1a-f4c3-4234-b162-bb47bc55ec57 c0ea0a74-c991-4005-ab6a-3a29f23e67b7
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=ice-ufrag:vPie
a=ice-pwd:QWp1jfvbc4iUBXfLVSxhDFIN
a=ice-options:trickle
a=fingerprint:sha-256 60:00:B9:57:5D:EC:CE:C7:7D:57:EA:EF:AF:37:23:64:63:39:F7:F3:D5:01:C7:18:C7:6E:B9:B4:46:19:40:06
a=setup:actpass
a=mid:2
a=rtcp-mux
a=recvonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-rsize
`;
